#!/bin/bash
# Onno Zweers, 2011-10-13
#
# Description:
#
# This plugin checks if CRLs are still valid.
#

# Nagios return codes
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

CHECK_NAME="CRL"

PROGNAME=`basename $0`

# Check some commands that we need
/usr/bin/which openssl 2>&1 1>/dev/null || exit $STATE_UNKNOWN


CRLDIR="/etc/grid-security/certificates"

# Set defaults
WARNING_HOURS=6
CRITICAL_HOURS=2

# Collect arguments
while getopts w:c:s: OPT $@; do
  case $OPT in
    w) # warning if less then n days
      WARNING_HOURS=$OPTARG
      ;;
    c) # critical if less than n days
      CRITICAL_HOURS=$OPTARG
      ;;
  esac
done

WARNING_SECONDS=$(($WARNING_HOURS * 3600))
CRITICAL_SECONDS=$(($CRITICAL_HOURS * 3600))


if [ ! -d "$CRLDIR" ] ; then
  echo "$CHECK_NAME UNKNOWN - CRL directory $CRLDIR not found."
  exit $STATE_UNKNOWN
fi

NOW=`date +%s`
CRITICAL=
WARNING=

cd "$CRLDIR"
for CRLFILE in *.r0 ; do
  NEXTUPDATE_STRING=`openssl crl -in "$CRLFILE" -noout -nextupdate 2>&1 | sed -e 's/nextUpdate=//'`
  NEXTUPDATE=`date +%s --date="$NEXTUPDATE_STRING" 2>&1`
  # Format is seconds sinds epoch. So it must be a number.
  if [[ ! "$NEXTUPDATE" =~ ^[0-9]+$ ]] ; then
    echo "$CHECK_NAME UNKNOWN: Could not get end date of the CRL $CRLFILE: $CRLNEXTDATE $NEXTUPDATE"
    exit $STATE_UNKNOWN
  fi
  SECONDS_LEFT=$(($NEXTUPDATE - $NOW))
  # Determine status
  if [ $SECONDS_LEFT -lt $CRITICAL_SECONDS ] ; then
    CRITICAL=yes
  fi
  if [ $SECONDS_LEFT -lt $WARNING_SECONDS ] ; then
    # Get the name of the CA from the ".0" symlink
    CA_SYMLINK=`echo $CRLFILE | sed -e 's/\.r0/.0/'`
    if [ -L "$CA_SYMLINK" ] ; then
      CA=`stat --format=%N $CA_SYMLINK | sed -e 's/.*-> .//' -e 's/\.pem.*//'`
      test -z "$CA" && CA="could not find CA name from symlink"
    elif [ -f "$CA_SYMLINK" ] ; then
      CA="related CA file is not a symlink"
    else
      CA="no related CA cert found"
    fi
    WARNING=yes
    if [ -z "$LIST" ] ; then
      LIST="$CRLFILE ($CA) valid until $NEXTUPDATE_STRING"
    else
      LIST="$LIST; $CRLFILE ($CA) valid until $NEXTUPDATE_STRING"
    fi
  fi
done

if [ "$CRITICAL" = "yes" ] ; then
  echo "$CHECK_NAME CRITICAL - At least one CRL less than $CRITICAL_HOURS hours valid - $LIST"
  exit $STATE_CRITICAL
fi

if [ "$WARNING" = "yes" ] ; then
  echo "$CHECK_NAME WARNING - At least one CRL less than $WARNING_HOURS hours valid - $LIST"
  exit $STATE_WARNING
fi

echo "$CHECK_NAME OK - CRLs in $CRLDIR are up to date."
exit $STATE_OK
