#!/bin/bash
# Onno Zweers, 2011-10-04
#
# Description:
#
# This Nagios/Icinga plugin checks how many days a Dell host is supported.
#
# Changes:
# 2012-03-12 - Onno - Caching, changed URL

# Nagios return codes
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

CHECK_NAME="DELL SUPPORT"

PROGNAME=`basename $0`

DELL_SUPPORT_URL="http://www.dell.com/support/troubleshooting/us/en/19/Index?ServiceTag="
CACHEDIR="/var/cache/dell_support_info"
mkdir --parents "$CACHEDIR"
CACHE_DAYS=31

# Check some commands that we need
/usr/bin/which dmidecode 2>&1 1>/dev/null || exit $STATE_UNKNOWN
/usr/bin/which lynx      2>&1 1>/dev/null || exit $STATE_UNKNOWN
/usr/bin/which perl      2>&1 1>/dev/null || exit $STATE_UNKNOWN


# Set defaults
WARNING_DAYS=90
CRITICAL_DAYS=30

# Collect arguments
while getopts w:c:s: OPT $@; do
  case $OPT in
    w) # warning if less then n days
      WARNING_DAYS=$OPTARG
      ;;
    c) # critical if less than n days
      CRITICAL_DAYS=$OPTARG
      ;;
    s) # specify serial number manually (if not, it's automatic)
      POWEREDGE_SERIAL_NUMBERS="$OPTARG"
      ;;
  esac
done

if [ -z "$POWEREDGE_SERIAL_NUMBERS" ] ; then
  # This host can have several serial numbers (blade & chassis)
  POWEREDGE_SERIAL_NUMBERS=`dmidecode | grep -2 PowerEdge | grep Serial | sed -e 's/.*Serial Number: //'`
  if [ -z "$POWEREDGE_SERIAL_NUMBERS" ] ; then
    echo "$CHECK_NAME UNKNOWN - Unable to get serial number with dmidecode. Am I running as root? Fix me or try specifying it with -s."
    exit $STATE_UNKNOWN
  fi
fi

ADDITIONAL_INFO="Checked serial numbers:"
for SERIAL in $POWEREDGE_SERIAL_NUMBERS ; do
  ADDITIONAL_INFO="$ADDITIONAL_INFO <a href='$DELL_SUPPORT_URL$SERIAL'>$SERIAL</a>"
done

for SERIAL in $POWEREDGE_SERIAL_NUMBERS ; do
  SUPPORT_LINES=`lynx -width=200 -dump $DELL_SUPPORT_URL$SERIAL | grep '\[[0-9]\+\] *days *remaining' | sed -e 's/ See the .*Warranty Tab for details//'`
  if [ -z "$SUPPORT_LINES" ] ; then
    # Perhaps website down. Do we have a recent cached version?
    if find "$CACHEDIR" -type f -name "$SERIAL" -mtime -$CACHE_DAYS | grep --silent . ; then
      SUPPORT_LINES=`cat "$CACHEDIR/$SERIAL"`
      CACHE_REMARK=" - Web page unavailable; using cached information."
    else
      echo "$CHECK_NAME UNKNOWN - Unable to get support information and cached info has expired. Check $DELL_SUPPORT_URL$SERIAL"
      exit $STATE_UNKNOWN
    fi
  else
    # Page collected succesfully; save in cache.
    echo "$SUPPORT_LINES" > "$CACHEDIR/$SERIAL"
  fi
  DAYS_LEFT=`echo "$SUPPORT_LINES" | grep -o '\[[0-9]\+\]' | grep -o '[0-9]\+' | sort -n | tail -n 1`
  # Collect info to display, format "line 1 - line 2"
  SUPPORT_INFO_TMP=`echo -e "$SUPPORT_LINES" | perl -p -e 's/\s+$/ - /g' | sed -e 's/ - $//'`
  SUPPORT_INFO=`echo $SUPPORT_INFO_TMP`
  # Determine status
  if [ $DAYS_LEFT -lt $CRITICAL_DAYS ] ; then
    echo "$CHECK_NAME CRITICAL - $DAYS_LEFT days of support left for <a href='$DELL_SUPPORT_URL$SERIAL'>$SERIAL</a>. - $ADDITIONAL_INFO - $SUPPORT_INFO $CACHE_REMARK"
    exit $STATE_CRITICAL
  fi
  if [ $DAYS_LEFT -lt $WARNING_DAYS ] ; then
    echo "$CHECK_NAME WARNING - $DAYS_LEFT days of support left for <a href='$DELL_SUPPORT_URL$SERIAL'>$SERIAL</a>. - $ADDITIONAL_INFO - $SUPPORT_INFO $CACHE_REMARK"
    exit $STATE_WARNING
  fi
done

echo "$CHECK_NAME OK - $DAYS_LEFT days of support left for <a href='$DELL_SUPPORT_URL$SERIAL'>$SERIAL</a>. - $ADDITIONAL_INFO - $SUPPORT_INFO $CACHE_REMARK"
exit $STATE_OK
