#!/bin/bash

# Uses MegaCli to check the status of disks attached to an LSI controller.
# Bugs: this check will probably fail if you have more than one adapter in a host.
# 2013-12-03 - Onno - Created.

# Nagios return codes
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

# Check if binaries exist.
/usr/bin/which dmidecode 2>&1 1>/dev/null || exit $STATE_UNKNOWN
MEGACLI="/opt/MegaRAID/MegaCli/MegaCli64"
if [ ! -x "$MEGACLI" ] ; then
  echo "UNKNOWN: File $MEGACLI is not found or not executable."
  exit $STATE_UNKNOWN
fi

SYSTEM_SN=`dmidecode | grep 'Base Board Information' -A 5 | grep 'Serial Number' | sed -e 's/.*: //'`

REPORT=""

for VIRTUAL_DRIVE in `$MEGACLI -LDInfo -Lall -aALL | grep -o 'Virtual Drive: [0-9]\+' | sed -e 's/.*: //'` ; do
  LDINFO=`$MEGACLI -LDInfo -L${VIRTUAL_DRIVE} -aALL`
  SIZE=`echo "$LDINFO" | grep '^Size' | sed -e 's/.*: //'`
  STATE=`echo "$LDINFO" | grep '^State' | sed -e 's/.*: //'`
  if [ "$STATE" != "Optimal" ] ; then
    if [ -z "$REPORT" ] ; then
      REPORT="Virtual drive $VIRTUAL_DRIVE ($SIZE): $STATE"
    else
      REPORT="$REPORT --- Virtual drive $VIRTUAL_DRIVE ($SIZE): $STATE"
    fi
  fi
done

for ENCLOSURE_ID in `$MEGACLI -PDList -aAll | grep "Enclosure Device" | awk '{print $4}' | sort -nu` ;do
  for SLOT in `$MEGACLI -PDList -aAll | grep -A 1 "Enclosure Device ID: $ENCLOSURE_ID" | grep "Slot Number" | awk '{print $3}'` ; do
    DISKINFO=`$MEGACLI -pdinfo -PhysDrv [$ENCLOSURE_ID:$SLOT] -aAll`
    DISK_TYPE=`echo "$DISKINFO" | grep 'PD Type:' | sed -e 's/.*: //'`
    DISK_WWN=`echo "$DISKINFO" | grep 'WWN:' | sed -e 's/.*: //'`
    DISK_SERIAL=`echo "$DISKINFO" | grep 'Inquiry Data:' | sed -e 's/.*: //'`
    SIZE=`echo "$DISKINFO" | grep 'Raw Size:' | sed -e 's/.*: //' | sed -e 's/ \[0x.*//'`
    ERRORLINES=`echo "$DISKINFO" | grep 'Count: [1-9]\|Firmware state: Failed'`
    if [ -n "$ERRORLINES" ] ; then
      DISKREPORT=""
      while read line ; do
        if [ -z "$DISKREPORT" ] ; then
          DISKREPORT=`echo Enclosure/slot [$ENCLOSURE_ID:$SLOT] WWN=$DISK_WWN $DISK_SERIAL "($SIZE)" - $line`
        else
          DISKREPORT="$DISKREPORT - `echo $line`"
        fi
      done < <(echo "$ERRORLINES")
      if [ -z "$REPORT" ] ; then
        REPORT="$DISKREPORT"
      else
        REPORT="$REPORT --- $DISKREPORT"
      fi
    fi
  done
done


if [ -z "$REPORT" ] ; then
  echo "OK - System S/N=$SYSTEM_SN: no disk problems found."
  exit $STATE_OK
else
  echo "CRITICAL - System S/N=$SYSTEM_SN: $REPORT"
  exit $STATE_CRITICAL
fi
